/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function calculateDamage(authorAtk: number, opponentDefense: number): number
export function add(left: number, right: number): number
