[package]
name = "my_rust_library"
version = "0.1.0"
edition = "2021"

[dependencies]
napi = { version = "2" }
napi-derive = { version = "2", default-features = true }

[lib]
crate-type = ["cdylib"]
[build-dependencies]
napi-build = "2"